version: '3.8'

services:
  web:
    entrypoint: /home/app/web/entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn baseballquery_backend.wsgi:application
    volumes:
      - ~/.baseballquery:/home/app/.baseballquery
      - ./lmdb_db:/home/app/web/lmdb_db
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  cron:
    build: .
    command: ["/usr/sbin/cron", "-f"]