version: '3.8'

services:
  web:
    build: .
    command: gunicorn baseballquery_backend.wsgi:application
    volumes:
      - ./:/usr/src/app/
      - ~/.baseballquery:/root/.baseballquery
      - ./lmdb_db:/usr/src/app/lmdb_db
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web