version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - ~/.baseballquery:/root/.baseballquery
      - ./lmdb_db:/usr/src/app/lmdb_db
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev