version: '3.8'

services:
  web:
    entrypoint: /home/app/web/entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn baseballquery_backend.wsgi:application
    volumes:
      - ~/.baseballquery:/home/app/.baseballquery
      - ./lmdb_db:/home/app/web/lmdb_db
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx