# Generated by Django 5.2.4 on 2025-07-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedquery",
            name="name",
        ),
    ]
